#!/bin/bash
export BBLOGAPIBBEVQUEUE='/usr/bb/sbin/logapibbevqueue'
export DYLD_LIBRARY_PATH=/usr/bb/lib:/usr/bb/local/lib
export LD_LIBRARY_PATH=/usr/bb/lib:/usr/bb/local/lib
ulimit -c unlimited
exec setuidgid bb $BBLOGAPIBBEVQUEUE