// Generated by the protocol buffer compiler.  DO NOT EDIT!

#include "bbprotobuf.pb.h"
#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format_inl.h>

namespace bb {

namespace {

const ::google::protobuf::Descriptor* IrcLog_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  IrcLog_reflection_ = NULL;
const ::google::protobuf::Descriptor* IrcLogs_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  IrcLogs_reflection_ = NULL;

}  // namespace


void protobuf_BuildDesc_bbprotobuf_2eproto_AssignGlobalDescriptors(const ::google::protobuf::FileDescriptor* file) {
  IrcLog_descriptor_ = file->message_type(0);
  IrcLog::default_instance_ = new IrcLog();
  IrcLog_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      IrcLog_descriptor_,
      IrcLog::default_instance_,
      IrcLog::_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(IrcLog, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(IrcLog, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    IrcLog_descriptor_, IrcLog::default_instance_);
  IrcLogs_descriptor_ = file->message_type(1);
  IrcLogs::default_instance_ = new IrcLogs();
  IrcLogs_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      IrcLogs_descriptor_,
      IrcLogs::default_instance_,
      IrcLogs::_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(IrcLogs, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(IrcLogs, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    IrcLogs_descriptor_, IrcLogs::default_instance_);
  IrcLog::default_instance_->InitAsDefaultInstance();
  IrcLogs::default_instance_->InitAsDefaultInstance();
}

void protobuf_BuildDesc_bbprotobuf_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;
  ::google::protobuf::DescriptorPool* pool =
    ::google::protobuf::DescriptorPool::internal_generated_pool();

  pool->InternalBuildGeneratedFile(
    "\n\020bbprotobuf.proto\022\002bb\"L\n\006IrcLog\022\017\n\007chan"
    "nel\030\001 \002(\t\022\014\n\004time\030\002 \002(\t\022\022\n\nidentifier\030\003 "
    "\002(\t\022\017\n\007message\030\004 \002(\t\"&\n\007IrcLogs\022\033\n\007irclo"
    "gs\030\001 \003(\0132\n.bb.IrcLog", 140,
  &protobuf_BuildDesc_bbprotobuf_2eproto_AssignGlobalDescriptors);
}

// Force BuildDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_bbprotobuf_2eproto {
  StaticDescriptorInitializer_bbprotobuf_2eproto() {
    protobuf_BuildDesc_bbprotobuf_2eproto();
  }
} static_descriptor_initializer_bbprotobuf_2eproto_;


// ===================================================================

const ::std::string IrcLog::_default_channel_;
const ::std::string IrcLog::_default_time_;
const ::std::string IrcLog::_default_identifier_;
const ::std::string IrcLog::_default_message_;
const int IrcLog::_offsets_[4] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(IrcLog, channel_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(IrcLog, time_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(IrcLog, identifier_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(IrcLog, message_),
};

IrcLog::IrcLog()
  : ::google::protobuf::Message(),
    _cached_size_(0),
    channel_(const_cast< ::std::string*>(&_default_channel_)),
    time_(const_cast< ::std::string*>(&_default_time_)),
    identifier_(const_cast< ::std::string*>(&_default_identifier_)),
    message_(const_cast< ::std::string*>(&_default_message_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void IrcLog::InitAsDefaultInstance() {}

IrcLog::IrcLog(const IrcLog& from)
  : ::google::protobuf::Message(),
    _cached_size_(0),
    channel_(const_cast< ::std::string*>(&_default_channel_)),
    time_(const_cast< ::std::string*>(&_default_time_)),
    identifier_(const_cast< ::std::string*>(&_default_identifier_)),
    message_(const_cast< ::std::string*>(&_default_message_)) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

IrcLog::~IrcLog() {
  if (channel_ != &_default_channel_) {
    delete channel_;
  }
  if (time_ != &_default_time_) {
    delete time_;
  }
  if (identifier_ != &_default_identifier_) {
    delete identifier_;
  }
  if (message_ != &_default_message_) {
    delete message_;
  }
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* IrcLog::descriptor() {
  if (IrcLog_descriptor_ == NULL) protobuf_BuildDesc_bbprotobuf_2eproto();
  return IrcLog_descriptor_;
}

const IrcLog& IrcLog::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_bbprotobuf_2eproto();
  return *default_instance_;
}

IrcLog* IrcLog::default_instance_ = NULL;

IrcLog* IrcLog::New() const {
  return new IrcLog;
}

const ::google::protobuf::Descriptor* IrcLog::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* IrcLog::GetReflection() const {
  if (IrcLog_reflection_ == NULL) protobuf_BuildDesc_bbprotobuf_2eproto();
  return IrcLog_reflection_;
}

// ===================================================================


const int IrcLogs::_offsets_[1] = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(IrcLogs, irclogs_),
};

IrcLogs::IrcLogs()
  : ::google::protobuf::Message(),
    _cached_size_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

void IrcLogs::InitAsDefaultInstance() {}

IrcLogs::IrcLogs(const IrcLogs& from)
  : ::google::protobuf::Message(),
    _cached_size_(0) {
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  MergeFrom(from);
}

IrcLogs::~IrcLogs() {
  if (this != default_instance_) {
  }
}

const ::google::protobuf::Descriptor* IrcLogs::descriptor() {
  if (IrcLogs_descriptor_ == NULL) protobuf_BuildDesc_bbprotobuf_2eproto();
  return IrcLogs_descriptor_;
}

const IrcLogs& IrcLogs::default_instance() {
  if (default_instance_ == NULL) protobuf_BuildDesc_bbprotobuf_2eproto();
  return *default_instance_;
}

IrcLogs* IrcLogs::default_instance_ = NULL;

IrcLogs* IrcLogs::New() const {
  return new IrcLogs;
}

const ::google::protobuf::Descriptor* IrcLogs::GetDescriptor() const {
  return descriptor();
}

const ::google::protobuf::Reflection* IrcLogs::GetReflection() const {
  if (IrcLogs_reflection_ == NULL) protobuf_BuildDesc_bbprotobuf_2eproto();
  return IrcLogs_reflection_;
}

}  // namespace bb
