BB_HOME=/usr/bb
all:
install:
	mkdir -p $(BB_HOME)/service
	cp -r ./bb_nginx $(BB_HOME)/service
	cp -r ./bb_ngircd $(BB_HOME)/service
	cp -r ./bb_bbircd $(BB_HOME)/service
	cp -r ./bb_memcached $(BB_HOME)/service
