BB_HOME=/usr/bb
all:
install:
	mkdir -p $(BB_HOME)/service
	cp -r ./bb_nginx $(BB_HOME)/service
	cp -r ./bb_ngircd $(BB_HOME)/service
	cp -r ./bb_bbircd $(BB_HOME)/service
	cp -r ./bb_memcached $(BB_HOME)/service
	cp -r ./bb_logapibbevqueue $(BB_HOME)/service
	cp -r ./bb_logapiserver $(BB_HOME)/service
	cp -r ./bb_searchapiserver $(BB_HOME)/service
	cp -r ./bb_evhttp_search_client $(BB_HOME)/service
