BB_UI_HOME=/usr/bb/htdocs
install:
	mkdir -p $(BB_UI_HOME)
	install -m644 index.html $(BB_UI_HOME)
	install -m644 join_channel.html $(BB_UI_HOME)
	install -m644 send_message.html $(BB_UI_HOME)
	install -m644 jquery-1.3.2.min.js $(BB_UI_HOME)
	install -m644 jquery.cookie.js $(BB_UI_HOME)
	install -m644 bbui.js $(BB_UI_HOME)

