#!/bin/sh
ARGV="$@"
BBIRCD='/usr/bb/sbin/bbircd'

ERROR=0
if [ "x$ARGV" = "x" ] ; then 
    ARGV="-h"
fi

start(){
    ulimit -c unlimited
    rm -rf /usr/bb/var/log/bbircd
    export DYLD_LIBRARY_PATH=/usr/bb/lib:/usr/bb/local/lib
    export LD_LIBRARY_PATH=/usr/bb/lib:/usr/bb/local/lib
    $BBIRCD > /usr/bb/var/log/bbircd &
    disown
    ERROR=$?
}

stop(){
    kill `pgrep bbircd`
    ERROR=$?
 }

case $ARGV in
start)
    start
    ;;
stop)
    stop
    ;;
restart)
    stop
    start 
esac

exit $ERROR

