#!/bin/bash
export BBSEARCHAPISERVER='/usr/bb/sbin/searchapiserver'
export DYLD_LIBRARY_PATH=/usr/bb/lib:/usr/bb/local/lib
export LD_LIBRARY_PATH=/usr/bb/lib:/usr/bb/local/lib
ulimit -c unlimited
exec setuidgid bb $BBSEARCHAPISERVER